name = "clfchub"
main = "src/index.js"
compatibility_date = "2026-08-19"

[[d1_databases]]
binding = "DB"
database_name = "clfchub"
database_id = "199c7c5a-b202-4439-9401-4c2f27e33ea5"

[vars]
PLAYHQ_ORG_ID = "89b6bccc-ad76-4766-8b96-9f1fc00738ec"

[triggers]
crons = [
  "0 12 * * 5", # Friday 20:00 Perth (UTC+8)
  "0 0 * * 6"   # Saturday 08:00 Perth (UTC+8)
]

[observability]
enabled = true
